---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
inputs:
  - name: pcf-pipelines
  - name: pcf-terraform-state
params:
  PEM:
  ERT_DOMAIN:
  db_aws_service_broker_username:
  db_aws_service_broker_password:
run:
  path: pcf-pipelines/install-aws-service-broker/tasks/prepare-rds/task.sh
