---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
inputs:
  - name: pcf-pipelines
  - name: terraform-state
outputs:
  - name: terraform-state-output
params:
  DB_MASTER_USERNAME:
  DB_MASTER_PASSWORD:
  TERRAFORM_PREFIX:
  TF_VAR_aws_access_key:
  TF_VAR_aws_secret_key:
  TF_VAR_aws_key_name:
  TF_VAR_aws_cert_arn:
  TF_VAR_aws_region:

run:
  path: pcf-pipelines/install-aws-service-broker/tasks/prepare-aws/task.sh
