---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
  - name: pcf-pipelines
  - name: json_file

run:
  path: pcf-pipelines/install-aws-service-broker/tasks/configure-service-broker/task.sh

params:
  pcf_iaas:
  pcf_ert_domain:
  pcf_opsman_admin:
  pcf_opsman_admin_passwd:
