---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
  - name: pcf-pipelines
  - name: terraform-state
  - name: pcf-terraform-state

outputs:
  - name: json_file

run:
  path: pcf-pipelines/install-aws-service-broker/tasks/configure-json/task.sh

params:
  pcf_iaas:
  pcf_ert_domain:
  pcf_opsman_admin:
  pcf_opsman_admin_passwd:
  pcf_az_1:
  pcf_az_2:
  pcf_az_3:
  pcf_ert_ssl_cert:
  pcf_ert_ssl_key:
  # IaaS Specific for GCP only
  gcp_storage_access_key:
  gcp_storage_secret_key:
  # aws specific
  S3_ENDPOINT:
  # db credentials
  db_aws_service_broker_username:
  db_aws_service_broker_password:
