resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: terraform-state
  type: s3
  source:
    disable_ssl: false
    access_key_id: {{TF_VAR_aws_access_key}}
    secret_access_key: {{TF_VAR_aws_secret_key}}
    endpoint: {{S3_ENDPOINT}}
    bucket: {{S3_OUTPUT_BUCKET}}
    region_name: {{S3_REGION}}
    versioned_file: terraform.tfstate

- name: pivnet-aws-service-broker
  type: pivnet
  check_every: 4h
  source:
    api_token: {{pivnet_token}}
    product_slug: aws-services
    product_version: {{aws_major_minor_version}}
    sort_by: semver

- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:cah-josephgeorge/pcf-pipelines.git
    branch: master
    private_key: {{git_private_key}}

jobs:
- name: upload-aws
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
      resource: pivnet-aws-service-broker
      params:
        globs:
        - "*pivotal"
    - get: terraform-state
      trigger: true
      passed: [deploy-director]
  - task: upload-tile
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      OPS_MGR_HOST: {{OPSMAN_URI}}
      OPS_MGR_USR: {{OPSMAN_USER}}
      OPS_MGR_PWD: {{OPSMAN_PASSWORD}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      IAAS: "aws"
      NO_PROXY: ""
      OM_IP: ""
  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_URI: {{OPSMAN_URI}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      PRODUCT_NAME: cf

- name: deploy-aws
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
      trigger: true
      passed: [upload-aws]

  - task: configure-json
    file: pcf-pipelines/tasks/install-aws/configure-json/task.yml
    params:
      pcf_iaas: aws
      pcf_ert_domain: {{ERT_DOMAIN}}
      pcf_opsman_admin: {{OPSMAN_USER}}
      pcf_opsman_admin_passwd: {{OPSMAN_PASSWORD}}
      pcf_ert_ssl_cert: {{ERT_SSL_CERT}}
      pcf_ert_ssl_key: {{ERT_SSL_KEY}}
      pcf_az_1: {{TF_VAR_az1}}
      pcf_az_2: {{TF_VAR_az2}}
      pcf_az_3: {{TF_VAR_az3}}
      terraform_template: default
      terraform_prefix: {{terraform_prefix}}
      S3_ENDPOINT: {{S3_ENDPOINT}}
      mysql_monitor_recipient_email: {{mysql_monitor_recipient_email}}
      MYSQL_BACKUPS: {{mysql_backups}}
      MYSQL_BACKUPS_SCP_SERVER: {{mysql_backups_scp_server}}
      MYSQL_BACKUPS_SCP_PORT: {{mysql_backups_scp_port}}
      MYSQL_BACKUPS_SCP_USER: {{mysql_backups_scp_user}}
      MYSQL_BACKUPS_SCP_KEY: {{mysql_backups_scp_key}}
      MYSQL_BACKUPS_SCP_DESTINATION: {{mysql_backups_scp_destination}}
      MYSQL_BACKUPS_SCP_CRON_SCHEDULE: {{mysql_backups_scp_cron_schedule}}
      MYSQL_BACKUPS_S3_ENDPOINT_URL: {{mysql_backups_s3_endpoint_url}}
      MYSQL_BACKUPS_S3_BUCKET_NAME: {{mysql_backups_s3_bucket_name}}
      MYSQL_BACKUPS_S3_BUCKET_PATH: {{mysql_backups_s3_bucket_path}}
      MYSQL_BACKUPS_S3_ACCESS_KEY_ID: {{mysql_backups_s3_access_key_id}}
      MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: {{mysql_backups_s3_secret_access_key}}
      MYSQL_BACKUPS_S3_CRON_SCHEDULE: {{mysql_backups_s3_cron_schedule}}

  - task: configure-aws
    file: pcf-pipelines/tasks/install-aws/configure-aws/task.yml
    params:
      pcf_iaas: aws
      pcf_ert_domain: {{ERT_DOMAIN}}
      pcf_opsman_admin: {{OPSMAN_USER}}
      pcf_opsman_admin_passwd: {{OPSMAN_PASSWORD}}

  - task: disable-errands
    file: pcf-pipelines/tasks/disable-errands/task.yml
    params:
      PRODUCT_NAME: cf
      OPSMAN_URI: {{OPSMAN_URI}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      ERRANDS_TO_DISABLE: {{aws_errands_to_disable}}

  - task: deploy-aws
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_URI: {{OPSMAN_URI}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
